/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import lexer.LexInter;
import java.io.*; import lexer.*; import parser.*;import asm.*;
import javax.swing.JFileChooser;

/**
 *
 * @author User
 */
public class GuiForMain extends javax.swing.JFrame {

    /**
     * Creates new form GuiForMain
     */
    public GuiForMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextField = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        samplecodeText = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        File = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);

        jButton1.setText("Run");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        TextField.setColumns(20);
        TextField.setRows(5);
        TextField.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TextFieldPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(TextField);

        samplecodeText.setColumns(20);
        samplecodeText.setRows(5);
        jScrollPane2.setViewportView(samplecodeText);

        jButton3.setText("Save");

        File.setText("Choose A file");
        File.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(File)
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addGap(85, 85, 85)
                .addComponent(jButton3)
                .addGap(158, 158, 158))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(File))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
                try{Action();
                
                }
                catch(IOException e){
                    
                }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void FileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileActionPerformed
        JFileChooser jFileChooser1 = new JFileChooser();
        int i = jFileChooser1.showOpenDialog(this);
        
        if(i == javax.swing.JFileChooser.APPROVE_OPTION){
            File file = jFileChooser1.getSelectedFile();
            String filepath = file.getPath();
            
            try{
               BufferedReader bufferedreader = new BufferedReader(new FileReader(filepath));
               String str1="",str2 ="";
               while((str1= bufferedreader.readLine())!=null){
                   str2+=str1+"\n";
               }
               samplecodeText.setText(str2);
               bufferedreader.close();
            }
            catch(Exception ex){
                ex.printStackTrace();
            }
            
            String inputCode = samplecodeText.getText();
            try {
                FileWriter f = new FileWriter("test.txt");
                BufferedWriter b = new BufferedWriter(f);
                b.write(inputCode);
                b.close();
            }
            catch(FileNotFoundException  e) { e.printStackTrace(); }
            catch(IOException ex) { ex.printStackTrace(); }

            }
        

    }//GEN-LAST:event_FileActionPerformed

    private void TextFieldPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TextFieldPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPropertyChange
public void Action() throws IOException {
            String inputCode = samplecodeText.getText();
            try {
                FileWriter f = new FileWriter("test.txt");
                BufferedWriter b = new BufferedWriter(f);
                b.write(inputCode);
                b.close();
            }
            catch(FileNotFoundException  e) { e.printStackTrace(); }
            catch(IOException ex) { ex.printStackTrace(); }
            
                LexInter li = new LexInter();
                Assembly assemb = new Assembly(li);
		Lexer lex = new Lexer();
		Parser parse = new Parser(lex, assemb);
                
                System.out.println("<Intermediate code>");
		parse.program();
		System.out.write('\n');
                System.out.println();
                System.out.println("<Assembly code>");
                String Display = assemb.program();
                
                TextField.setText(Display);
	}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiForMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiForMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiForMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiForMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiForMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton File;
    private javax.swing.JTextArea TextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea samplecodeText;
    // End of variables declaration//GEN-END:variables
}
